//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUploads.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class fileupload
    {
        [DisplayName("FileName")]
        [Required(ErrorMessage = "File Name Required")]
        public string filename { get; set; }

        public int id { get; set; }

        [DisplayName("Browse File")]
        [Required(ErrorMessage = "Upload a File")]
        public string file_path { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
